config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  mount ActionCable.server => '/cable'
  
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  
  devise_scope :user do
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :genres, only: [:index, :new, :create, :destroy]
    end
  end
  
  get '/admin', to: redirect('/')
  get '/admin/*path', to: redirect('/')
  
  resources :users, only: [:show] do
    member do
      get :following, :followers
      post 'follow', to: 'relationships#create'
      delete 'unfollow', to: 'relationships#destroy'
    end
    resources :posts, only: [:index]
  end
  
  resources :some, only: [:index, :show, :edit, :update, :destroy]
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
      collection do
       get 'search'
       get 'genre_search'
       get 'tag_search'
      end
  end
  
  resources :groups do
    resources :members
    resources :events, only: [:create, :index]
    resources :group_users, only: [:create, :destroy]
    resources :messages, only: [:create]
    delete 'remove_member/:user_id', to: 'groups#remove_member', as: 'remove_member'
  end
  
  resources :events
  
  resources :chats, only: [:create]
  resources :chat_rooms, only: [:index, :show]
  #root to: 'posts#index'
  
  get 'search', to: 'posts#search'
  get 'tag_search', to: 'posts#tag_search'
end

app/models/chat.rb
class Chat < ApplicationRecord
  
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  belongs_to :user
  belongs_to :chat_room
  # メッセージの内容を保存するためのカラムが必要
  
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  
  has_many :chats, dependent: :destroy
  has_many :users, through: :chats
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_and_belongs_to_many :posts
  
  validates :name, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ApplicationRecord
  
  belongs_to :owner, class_name: 'User'
  
  has_many :events, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :messages, dependent: :destroy
  
  def self.search(search)
    if search.present?
      Group.where('name LIKE ? OR purpose LIKE ?', "%#{search}%", "%#{search}%")
    else
      Group.none
    end
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
  
  validates :user_id, uniqueness: { scope: :group_id }
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/member.rb
class Member < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :genres
  
  validates :title, presence: true
  validates :content, presence: true
  
  has_many :post_tags
  has_many :tags, through: :post_tags
  
  validate :tags_presence

  private

  def tags_presence
    errors.add(:tags, "can't be blank") if tags.empty?
  end
  # has_and_belongs_to_many :tags
  
  #validates :genre, presence: true
  # acts_as_taggable_on :tags など、タグ機能を追加する場合はここに記述
  
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  
  belongs_to :post
  belongs_to :tag
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :post_tags
  has_many :posts, through: :post_tags
  
  # has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :image
  
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
  
  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :chats, foreign_key: :sender_id
  has_many :owned_groups, class_name: 'Group', foreign_key: :owner_id
  #has_many :groups, foreign_key: :owner_id
  # 他の関連付けもここに追加
  
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    # 必要に応じて他の属性を設定
    end
  end
  
  def guest?
    email == 'guest@example.com'
  end
  
  def following?(other_user)
    following.include?(other_user)
  end
  
  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end
  
  def following_count
    self.following.count
  end
  
  def followers_count
    self.followers.count
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  before_action :set_group, only: [:edit, :update, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]
  
  def index
    if params[:search].present?
      @groups = Group.search(params[:search])
      if @groups.empty?
        flash[:alert] = '検索結果はありません。'
      end
    else
      @groups = Group.none
      flash[:alert] = '検索欄が空です。何かキーワードを入力してください。'
    end
  end
  
  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
    @groups = params[:search].present? ? Group.search(params[:search]) : Group.all
  end

  def create
    @group = Group.new(group_params)
    @group.owner = current_user
  if @group.save
    #ownerのgroup_userを登録
    @group_user = GroupUser.new
    @group_user.group_id = @group.id
    @group_user.user_id = @group.owner_id
    @group_user.save
    redirect_to new_group_path, notice: 'グループを作成しました'
  else
    render :new
  end
  end

  def edit
  end

  def update
  end
  
  def destroy
    @group.destroy
    redirect_to new_group_path, notice: 'グループを削除しました'
  end
  
  def remove_member
    group = Group.find(params[:group_id])
    user = User.find(params[:user_id])
    if group.owner == current_user
      group.users.delete(user)
      redirect_to group_members_path(group), notice: "#{user.name}をグループから脱退させました"
    else
      redirect_to group_path(group), alert: "権限がありません"
    end
  end
  
  private
  
  def set_group
    @group = Group.find(params[:id])
  end
  
  def group_params
    params.require(:group).permit(:name, :purpose)
  end
  
  def check_owner
    unless @group.owner == current_user
      redirect_to groups_path, alert: 'You are not authorized to perform this action.'
    end
  end
  
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/some_helper.rb
module SomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/index.html.erb
<div class="posts-index">
  <h2>検索結果</h2>

<div class="group-list">
  <% if @groups.empty? %>
    <p>検索結果はありません</p>
  <% else %>
  <% @groups.each do |group| %>
    <div class="group-items-container">
      <h2 class="group-item-title"><%= group.name %></h2>
      <div class="group-item-purpose"><%= group.purpose %></div>
      <% if group.owner == current_user || current_user.admin? %>
        <%= link_to 'グループを削除', group, method: :delete, data: { confirm: '本当によろしいですか？' }, class: "group-delete-btn" %>
      <% end %>
      <% unless group.owner == current_user || current_user.groups.include?(group) %>
        <%= button_to 'グループに参加', group_group_users_path(group), method: :post, class: "group-join-btn" %>
      <% end %>
    </div>
  <% end %>
  <% end %>
</div>
</div>

app/views/groups/new.html.erb
<div class="group-container">
  <h1 class="group-title">新規グループ作成</h1>

  <%= form_with(model: @group, local: true, html: { class: "group-form" }) do |f| %>
    <div class="group-form-group">
      <%= f.label :name, 'グループ名', class: "group-form-label" %>
      <%= f.text_field :name, class: "group-form-control" %>
    </div>

    <div class="group-form-group">
      <%= f.label :purpose, 'グループの目的', class: "group-form-label" %>
      <%= f.text_area :purpose, class: "group-form-control" %>
    </div>

    <%= f.submit 'グループを作成', class: "group-submit-btn" %>
  <% end %>
</div>

<h2 class="group-list-title">グループ一覧</h2>

<div class="group-list">
  <% @groups.each do |group| %>
    <div class="group-items-container">
      <h2 class="group-item-title"><%= group.name %></h2>
      <div class="group-item-purpose"><%= group.purpose %></div>
      <% if group.owner == current_user || current_user.admin? %>
        <%= link_to 'グループを削除', group, method: :delete, data: { confirm: '本当によろしいですか？' }, class: "group-delete-btn" %>
      <% end %>
      <% unless group.owner == current_user || current_user.groups.include?(group) %>
        <%= button_to 'グループに参加', group_group_users_path(group), method: :post, class: "group-join-btn" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="menu">
  <%= button_to 'イベント', group_events_path(@group), method: :get, class: 'menu-button' %>
  <%= button_to 'メッセージ', group_path(@group), method: :get, class: 'menu-button' %>
  <%= button_to 'グループメンバー', group_members_path(@group), method: :get, class: 'menu-button' %>
  <% if @group.group_users.find_by(user_id: current_user.id) %>
    <%= button_to 'グループを脱退', group_group_user_path(@group, current_user), method: :delete, data: { confirm: '本当に脱退しますか？' } %>
  <% end %>
</div>

<div class="chat-room">
  <div id="messages_<%= @group.id %>" class="messages">
    <% @group.messages.each do |message| %>
      <div class="message<%= ' message-self' if message.user == current_user %>">
        <strong><%= message.user.name %></strong>：<%= message.content %>
      </div>
    <% end %>
  </div>

  <%= form_with(model: [ @group, Message.new ], url: group_messages_path(@group), local: false, html: { class: "message-form" }) do |f| %>
    <%= f.text_area :content, class: "message-textarea", placeholder: 'メッセージを入力...' %>
    <%= f.submit '送信', class: "message-submit" %>
  <% end %>
</div>

app/views/groups/update.html.erb
<h1>Groups#update</h1>
<p>Find me in app/views/groups/update.html.erb</p>