config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  mount ActionCable.server => '/cable'
  
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  
  devise_scope :user do
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :genres, only: [:index, :new, :create, :destroy]
    end
  end
  
  get '/admin', to: redirect('/')
  get '/admin/*path', to: redirect('/')
  
  resources :users, only: [:show] do
    member do
      get :following, :followers
      post 'follow', to: 'relationships#create'
      delete 'unfollow', to: 'relationships#destroy'
    end
    resources :posts, only: [:index]
  end
  
  resources :some, only: [:index, :show, :edit, :update, :destroy]
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
      collection do
       get 'search'
       get 'genre_search'
       get 'tag_search'
      end
  end
  
  resources :groups do
    resources :members
    resources :events, only: [:create, :index]
    resources :group_users, only: [:create, :destroy]
    resources :messages, only: [:create]
    delete 'remove_member/:user_id', to: 'groups#remove_member', as: 'remove_member'
  end
  
  resources :events
  
  resources :chats, only: [:create]
  resources :chat_rooms, only: [:index, :show]
  #root to: 'posts#index'
  
  get 'search', to: 'posts#search'
  get 'tag_search', to: 'posts#tag_search'
end

app/models/chat.rb
class Chat < ApplicationRecord
  
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  belongs_to :user
  belongs_to :chat_room
  # メッセージの内容を保存するためのカラムが必要
  
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  
  has_many :chats, dependent: :destroy
  has_many :users, through: :chats
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_and_belongs_to_many :posts
  
  validates :name, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ApplicationRecord
  
  belongs_to :owner, class_name: 'User'
  
  has_many :events, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :messages, dependent: :destroy
  
  def self.search(search)
    if search.present?
      Group.where('name LIKE ? OR purpose LIKE ?', "%#{search}%", "%#{search}%")
    else
      Group.none
    end
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
  
  validates :user_id, uniqueness: { scope: :group_id }
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/member.rb
class Member < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :genres
  
  validates :title, presence: true
  validates :content, presence: true
  
  has_many :post_tags
  has_many :tags, through: :post_tags
  
  validate :tags_presence

  private

  def tags_presence
    errors.add(:tags, "can't be blank") if tags.empty?
  end
  # has_and_belongs_to_many :tags
  
  #validates :genre, presence: true
  # acts_as_taggable_on :tags など、タグ機能を追加する場合はここに記述
  
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  
  belongs_to :post
  belongs_to :tag
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :post_tags
  has_many :posts, through: :post_tags
  
  # has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :image
  
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
  
  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :chats, foreign_key: :sender_id
  has_many :owned_groups, class_name: 'Group', foreign_key: :owner_id
  #has_many :groups, foreign_key: :owner_id
  # 他の関連付けもここに追加
  
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    # 必要に応じて他の属性を設定
    end
  end
  
  def guest?
    email == 'guest@example.com'
  end
  
  def following?(other_user)
    following.include?(other_user)
  end
  
  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end
  
  def following_count
    self.following.count
  end
  
  def followers_count
    self.followers.count
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    def guest_sign_in
      user = User.guest
      sign_in user
      redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :admin_user, only: :destroy
  
  def show
    @user = User.find(params[:id])
    @liked_posts = @user.likes.map(&:post)
    @groups = @user.groups
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def following
    @user = User.find(params[:id])
    @following = @user.following
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
  end

  private

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
  
  
  # 他のアクションもここに追加します
  
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/some_helper.rb
module SomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<h1><%= @user.name %>のフォロワー</h1>

<ul>
  <% @followers.each do |follower| %>
    <li>
      <%= link_to follower.name, user_path(follower) %>
    </li>
  <% end %>
</ul>

app/views/users/following.html.erb
<h1><%= @user.name %>のフォロー</h1>

<ul>
  <% @following.each do |following| %>
    <li>
      <%= link_to following.name, user_path(following) %>
    </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p>
    <%= user.name %>
    <% if current_user.admin? %>
      <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ユーザープロフィール</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div class="gamer-profile">
    <h2>プロフィール</h2>

    <% if @user.image.attached? %>
      <%= image_tag @user.image, class: "profile-image" %>
    <% end %>

    <p>名前: <%= @user.name %></p>
    <% if current_user.admin? || current_user == @user %>
      <p>メールアドレス: <%= @user.email %></p>
    <% end %>
    <p>自己紹介: <%= @user.introduction %></p>

    <% if @user == current_user %>
      <%= link_to "プロフィールを編集", edit_user_registration_path %>
    <% elsif current_user.admin? %>
      <%= link_to 'ユーザーを削除', @user, method: :delete, data: { confirm: '本当に削除しますか？' } %>
    <% else %>
      <%= form_with(model: [Chat.new], local: true) do |f| %>
        <%= f.hidden_field :receiver_id, value: @user.id %>
        <!--<%= f.text_area :message, placeholder: 'メッセージを入力...' %>-->
        <!--<%= f.submit 'DMを送る' %>-->
      <% end %>
    <% end %>

    <h3>「いいね」した投稿</h3>

    <% @liked_posts.each do |post| %>
      <div class="post">
        <h4>タイトル: <%= post.title %></h4>
        <p>内容: <%= post.content %></p>
      </div>
    <% end %>

    <% unless current_user == @user %>
      <% if current_user.following?(@user) %>
        <%= button_to 'フォローを外す', unfollow_user_path(@user), method: :delete %>
      <% else %>
        <%= button_to 'フォローする', follow_user_path(@user) %>
      <% end %>
    <% end %>

    <p>フォロー数: <%= link_to @user.following_count, following_user_path(@user) %></p>
    <p>フォロワー数: <%= link_to @user.followers_count, followers_user_path(@user) %></p>
    
    <h3>作成したグループ</h3>
    <% @user.owned_groups.each do |group| %>
      <div>
        <h3><%= link_to group.name, group_path(group) %></h3>
        <p><%= group.purpose %></p>
      </div>
    <% end %>
    
    <h3>所属しているグループ</h3>
    <ul>
      <% @groups.each do |group| %>
        <li><%= link_to group.name, group_path(group) %></li>
      <% end %>
    </ul>

  </div>
</body>
</html>