config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  mount ActionCable.server => '/cable'
  
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  
  devise_scope :user do
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  authenticate :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :genres, only: [:index, :new, :create, :destroy]
    end
  end
  
  get '/admin', to: redirect('/')
  get '/admin/*path', to: redirect('/')
  
  resources :users, only: [:show] do
    member do
      get :following, :followers
      post 'follow', to: 'relationships#create'
      delete 'unfollow', to: 'relationships#destroy'
    end
    resources :posts, only: [:index]
  end
  
  resources :some, only: [:index, :show, :edit, :update, :destroy]
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
      collection do
       get 'search'
       get 'genre_search'
       get 'tag_search'
      end
  end
  
  resources :groups do
    resources :members
    resources :events, only: [:create, :index]
    resources :group_users, only: [:create, :destroy]
    resources :messages, only: [:create]
    delete 'remove_member/:user_id', to: 'groups#remove_member', as: 'remove_member'
  end
  
  resources :events
  
  resources :chats, only: [:create]
  resources :chat_rooms, only: [:index, :show]
  #root to: 'posts#index'
  
  get 'search', to: 'posts#search'
  get 'tag_search', to: 'posts#tag_search'
end

app/models/chat.rb
class Chat < ApplicationRecord
  
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  belongs_to :user
  belongs_to :chat_room
  # メッセージの内容を保存するためのカラムが必要
  
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  
  has_many :chats, dependent: :destroy
  has_many :users, through: :chats
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_and_belongs_to_many :posts
  
  validates :name, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ApplicationRecord
  
  belongs_to :owner, class_name: 'User'
  
  has_many :events, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :messages, dependent: :destroy
  
  def self.search(search)
    if search.present?
      Group.where('name LIKE ? OR purpose LIKE ?', "%#{search}%", "%#{search}%")
    else
      Group.none
    end
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
  
  validates :user_id, uniqueness: { scope: :group_id }
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/member.rb
class Member < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :genres
  
  validates :title, presence: true
  validates :content, presence: true
  
  has_many :post_tags
  has_many :tags, through: :post_tags
  
  validate :tags_presence

  private

  def tags_presence
    errors.add(:tags, "can't be blank") if tags.empty?
  end
  # has_and_belongs_to_many :tags
  
  #validates :genre, presence: true
  # acts_as_taggable_on :tags など、タグ機能を追加する場合はここに記述
  
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  
  belongs_to :post
  belongs_to :tag
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :post_tags
  has_many :posts, through: :post_tags
  
  # has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :image
  
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
  
  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :chats, foreign_key: :sender_id
  has_many :owned_groups, class_name: 'Group', foreign_key: :owner_id
  #has_many :groups, foreign_key: :owner_id
  # 他の関連付けもここに追加
  
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    # 必要に応じて他の属性を設定
    end
  end
  
  def guest?
    email == 'guest@example.com'
  end
  
  def following?(other_user)
    following.include?(other_user)
  end
  
  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end
  
  def following_count
    self.following.count
  end
  
  def followers_count
    self.followers.count
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @post = Post.new
    if params[:genre_id].present?
      @posts = Post.joins(:genres).where(genres: { id: params[:genre_id] }).order(created_at: :desc)
    else
      @posts = Post.order(created_at: :desc)
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)

    # カンマ区切りの文字列から配列に変換し、Tagモデルのインスタンスを見つけるか新しく作成する
    tag_names = params[:post][:tags].split(',').map(&:strip)
    tags = tag_names.map { |name| Tag.find_or_create_by(name: name) }
    @post.tags = tags

    if @post.save
      redirect_to posts_path
    else
      @posts = Post.all
      render :index
    end
  end
  
  def update
    @post = Post.find(params[:id])
  
    if @post.update(post_params.except(:tags))
      assign_tags(@post, post_params[:tags])
      redirect_to post_path(@post)
    else
      render :edit
    end
  end
  
  def search
    if params[:keyword].present?
      @posts = Post.where('content LIKE ?', "%#{params[:keyword]}%")
    else
      @posts = []
      flash[:alert] = '検索欄が空です。何かキーワードを入力してください。'
    end
  end
  
  def tag_search
    if params[:tags].present?
      @posts = Post.joins(:tags).where(tags: { name: params[:tags].split(',') })
    else
      @posts = []
      flash[:alert] = '検索欄が空です。何かキーワードを入力してください。'
    end
  end
  
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: '投稿を削除しました'
  end

  private

  def assign_tags(post, tag_names)
    post.tags.clear # 既存のタグをクリア
    tag_names.each do |tag_name|
      # 文字列からTagモデルのインスタンスを見つけるか、新しく作成する
      tag = Tag.find_or_create_by(name: tag_name)
      post.tags << tag
    end
  end
  
  def post_params
    params.require(:post).permit(:title, :content, :public)
  end
  
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/some_helper.rb
module SomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form.label :genre %>
<%= form.select :genre, ['ジャンル1', 'ジャンル2', 'ジャンル3'] %>

<%= form.label :tags, "タグ" %>
<%= form.text_field :tags, value: @post.tags.join(',') %>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= f.label :title, 'タイトル' %>
  <%= f.text_field :title %>

  <%= f.label :content, '内容' %>
  <%= f.text_area :content %>

  <%= f.label :genre, 'ジャンル' %>
  <%= f.select :genre, Post.genres.keys %>

  <%= f.label :tags, 'タグ（カンマ区切り）' %>
  <%= f.text_field :tags, value: @post.tags.map(&:name).join(',') %>

  <%= f.submit '更新する' %>
<% end %>

app/views/posts/index.html.erb
<body class="home-index">
<div class="posts-index">
  <h2>投稿一覧</h2>
  
<% unless current_user.guest? %>
<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_with model: @post, local: true do |f| %>
  <%= f.label :title, "タイトル" %>
  <%= f.text_field :title %>

  <%= f.label :content, "内容" %>
  <%= f.text_area :content %>
  
  <!--<%= f.label :genre_ids, "ジャンルの選択" %>
  <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name, include_hidden: false %>-->
  
  <%= f.label :tags, 'タグ（カンマ区切り）' %>
  <%= f.text_field :tags, name: 'post[tags]', value: @post.tags.map(&:name).join(", ") %>
  
  <%= f.label :public, '公開設定' %>
  <%= f.select :public, [['公開', true], ['非公開', false]] %>

  <%= f.submit "投稿" %>
<% end %>
<% end %>

  <% @posts.each do |post| %>
   <% if post.public || post.user == current_user %>
    <div class="post">
      <h3><%= link_to post.title, post_path(post) %></h3>
      <p>投稿者：<%= link_to post.user.name, user_path(post.user) %></p>
      <p>内容：<%= post.content %></p>
      <!--<div>ジャンル：
        <% post.genres.each do |genre| %>
          <%= genre.name %>
        <% end %>
      </div>-->
      <div>タグ：
        <% post.tags.each do |tag| %>
          <%= tag.name %>
        <% end %>
      </div>
      
      <% if !post.public && post.user == current_user %>
          <p>この投稿は非公開です。</p>
      <% end %>
      
      <% if post.user == current_user || current_user.admin? %>
        <%= link_to '削除', post_path(post), method: :delete, data: { confirm: '本当に削除しますか？' } %>
      <% end %>
      
      <% if post.likes.find_by(user_id: current_user.id) %>
        <%= link_to 'いいねを取り消す', post_likes_path(post), method: :delete %>
      <% else %>
        <%= link_to 'いいね', post_likes_path(post), method: :post %>
      <% end %>
      
      <p>いいね数：<%= post.likes.count %></p>
      
      <% post.comments.first(3).each do |comment| %>
        <p class="comment"><%= comment.user.name %>：<%= comment.content %></p>
        <% if comment.user == current_user || post.user == current_user || current_user.admin? %>
          <%= link_to 'コメントを削除', post_comment_path(post, comment), method: :delete, data: { confirm: '本当に削除しますか？' } %>
        <% end %>
      <% end %>

      <% if post.comments.count > 3 %>
        <div class="hidden_comments" style="display: none;">
          <% post.comments.drop(3).each do |comment| %>
            <p class="comment"><%= comment.user.name %>：<%= comment.content %></p>
          <% end %>
        </div>
        <button class="show_comments">その他のコメント</button>
      <% end %>
      
      <div id="comments_<%= post.id %>"></div>
      <%= form_with(model: [post, Comment.new], local: false) do |f| %>
        <%= f.text_area :content, placeholder: 'コメントを入力...' %>
        <%= f.submit 'コメントする' %>
      <% end %>
      
      
    </div>
    <% end %>
  <% end %>
</div>

</body>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= form_with model: @post, local: true do |f| %>
  <%= f.label :title, "タイトル" %>
  <%= f.text_field :title %>

  <%= f.label :content, "内容" %>
  <%= f.text_area :content %>
  
  <%= f.label :genre_ids, "ジャンルの選択" %>
  <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name, include_hidden: false %>
  
  <%= f.label :tags, 'タグ（カンマ区切り）' %>
  <%= f.text_field :tags, value: "" %>

  <%= f.submit "投稿" %>
<% end %>

app/views/posts/search.html.erb
<body class="home-index">
<div class="posts-index">
  <h2>検索結果</h2>
  
  <% if @posts.empty? %>
    <p>検索結果はありません。</p>
  <% else %>
  <% @posts.each do |post| %>
   <% if post.public || post.user == current_user %>
    <div class="post">
      <h3><%= link_to post.title, post_path(post) %></h3>
      <p>投稿者：<%= link_to post.user.name, user_path(post.user) %></p>
      <p>内容：<%= post.content %></p>
      <!--<div>ジャンル：
        <% post.genres.each do |genre| %>
          <%= genre.name %>
        <% end %>
      </div>-->
      <div>タグ：
        <% post.tags.each do |tag| %>
          <%= tag.name %>
        <% end %>
      </div>
      
      <% if !post.public && post.user == current_user %>
          <p>この投稿は非公開です。</p>
      <% end %>
      
      <% if post.user == current_user || current_user.admin? %>
        <%= link_to '削除', post_path(post), method: :delete, data: { confirm: '本当に削除しますか？' } %>
      <% end %>
      
      <% if post.likes.find_by(user_id: current_user.id) %>
        <%= link_to 'いいねを取り消す', post_likes_path(post), method: :delete %>
      <% else %>
        <%= link_to 'いいね', post_likes_path(post), method: :post %>
      <% end %>
      
      <p>いいね数：<%= post.likes.count %></p>
      
      <% post.comments.first(3).each do |comment| %>
        <p class="comment"><%= comment.user.name %>：<%= comment.content %></p>
        <% if comment.user == current_user || post.user == current_user || current_user.admin? %>
          <%= link_to 'コメントを削除', post_comment_path(post, comment), method: :delete, data: { confirm: '本当に削除しますか？' } %>
        <% end %>
      <% end %>

      <% if post.comments.count > 3 %>
        <div class="hidden_comments" style="display: none;">
          <% post.comments.drop(3).each do |comment| %>
            <p class="comment"><%= comment.user.name %>：<%= comment.content %></p>
          <% end %>
        </div>
        <button class="show_comments">その他のコメント</button>
      <% end %>
      
      <div id="comments_<%= post.id %>"></div>
      <%= form_with(model: [post, Comment.new], local: false) do |f| %>
        <%= f.text_area :content, placeholder: 'コメントを入力...' %>
        <%= f.submit 'コメントする' %>
      <% end %>
      
      
    </div>
    <% end %>
  <% end %>
  <% end %>
</div>

</body>

app/views/posts/show.html.erb
<body class="home-index">
<div class="posts-index">
  <h2>投稿詳細</h2>


  <div class="post">
    <h3><%= link_to @post.title, post_path(@post) %></h3>
    <p>投稿者：<%= link_to @post.user.name, user_path(@post.user) %></p>
    <p>内容：<%= @post.content %></p>
    <p>ジャンル：
      <% @post.genres.each do |genre| %>
        <%= genre.name %>
      <% end %>
    </p>
    <p>タグ：
      <% @post.tags.each do |tag| %>
        <%= tag.name %>
      <% end %>
    </p>
    
    <% if @post.user == current_user || current_user.admin? %>
      <%= form_with model: @post, local: true do |f| %>
        <%= f.label :public, '公開設定' %>
        <%= f.select :public, [['公開', true], ['非公開', false]] %>
        <%= f.submit "更新" %>
      <% end %>
      <%= link_to '削除', post_path(@post), method: :delete, data: { confirm: '本当に削除しますか？' } %>
    <% end %>
    
    <% if @post.user == current_user || current_user.admin? %>
      <%= link_to '削除', post_path(@post), method: :delete, data: { confirm: '本当に削除しますか？' } %>
    <% end %>
    
    <% if @post.likes.find_by(user_id: current_user.id) %>
      <%= link_to 'いいねを取り消す', post_likes_path(@post), method: :delete %>
    <% else %>
      <%= link_to 'いいね', post_likes_path(@post), method: :post %>
    <% end %>
    
    <p>いいね数：<%= @post.likes.count %></p>
    
    <% @post.comments.first(3).each do |comment| %>
      <p class="comment"><%= comment.user.name %>：<%= comment.content %></p>
    <% end %>

    <% if @post.comments.count > 3 %>
      <div class="hidden_comments" style="display: none;">
        <% @post.comments.drop(3).each do |comment| %>
          <p class="comment"><%= comment.user.name %>：<%= comment.content %></p>
        <% end %>
      </div>
      <button class="show_comments">その他のコメント</button>
    <% end %>
    
    <div id="comments_<%= @post.id %>"></div>
    <%= form_with(model: [@post, Comment.new], local: false) do |f| %>
      <%= f.text_area :content, placeholder: 'コメントを入力...' %>
      <%= f.submit 'コメントする' %>
    <% end %>
  </div>
</div>

</body>

app/views/posts/tag_search.html.erb
<div class="posts-index">
  <h2>投稿一覧（タグ検索結果）</h2>
  
  <% if @posts.empty? %>
    <p>検索結果はありません。</p>
  <% else %>
<% @posts.each do |post| %>
   <% if post.public || post.user == current_user %>
    <div class="post">
      <h3><%= link_to post.title, post_path(post) %></h3>
      <p>投稿者：<%= link_to post.user.name, user_path(post.user) %></p>
      <p>内容：<%= post.content %></p>
      <!--<div>ジャンル：
        <% post.genres.each do |genre| %>
          <%= genre.name %>
        <% end %>
      </div>-->
      <div>タグ：
        <% post.tags.each do |tag| %>
          <%= tag.name %>
        <% end %>
      </div>
      
      <% if !post.public && post.user == current_user %>
          <p>この投稿は非公開です。</p>
      <% end %>
      
      <% if post.user == current_user || current_user.admin? %>
        <%= link_to '削除', post_path(post), method: :delete, data: { confirm: '本当に削除しますか？' } %>
      <% end %>
      
      <% if post.likes.find_by(user_id: current_user.id) %>
        <%= link_to 'いいねを取り消す', post_likes_path(post), method: :delete %>
      <% else %>
        <%= link_to 'いいね', post_likes_path(post), method: :post %>
      <% end %>
      
      <p>いいね数：<%= post.likes.count %></p>
      
      <% post.comments.first(3).each do |comment| %>
        <p class="comment"><%= comment.user.name %>：<%= comment.content %></p>
        <% if comment.user == current_user || post.user == current_user || current_user.admin? %>
          <%= link_to 'コメントを削除', post_comment_path(post, comment), method: :delete, data: { confirm: '本当に削除しますか？' } %>
        <% end %>
      <% end %>

      <% if post.comments.count > 3 %>
        <div class="hidden_comments" style="display: none;">
          <% post.comments.drop(3).each do |comment| %>
            <p class="comment"><%= comment.user.name %>：<%= comment.content %></p>
          <% end %>
        </div>
        <button class="show_comments">その他のコメント</button>
      <% end %>
      
      <div id="comments_<%= post.id %>"></div>
      <%= form_with(model: [post, Comment.new], local: false) do |f| %>
        <%= f.text_area :content, placeholder: 'コメントを入力...' %>
        <%= f.submit 'コメントする' %>
      <% end %>
      
      
    </div>
     
    <% end %>
   <% end %>
  <% end %>
</div>